PLAT-864 Terraform SDK Upgrade
depop/terraform-provider-catalog pull request #12
Opened 2021-04-15 16:52 UTC by rjinskidepop

2021-04-16 10:26 UTC, 0x91 requested changes
we should pass through the new ctx into the catalog API client, otherwise we might hold up cancellations etc.

2021-04-16 10:26 UTC, 0x91 commented on catalog/data_source_catalog_env.go
> +func dataSourceCatalogEnvDistinctRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
getServices should be refactored to use the context from the provider, currently it creates a TODO context

2021-04-16 10:26 UTC, 0x91 commented on catalog/data_source_catalog_sandbox_kebab.go
> +func dataSourceCatalogSandboxKebabDistinctRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
same comment as for dataSourceCatalogEnvDistinctRead

2021-04-19 09:31 UTC, rjinskidepop commented
```
make testacc
==> Checking that code complies with gofmt requirements...
go test $(go list ./... |grep -v 'vendor') -cover -timeout 120m
?   	github.com/depop/terraform-provider-catalog	[no test files]
ok  	github.com/depop/terraform-provider-catalog/catalog	173.107s	coverage: 78.9% of statements
```

Time to run acceptance tests has increased but I assume this is the change to the testing strategy of the SDK. Everything looks correct and in-place 👍🏻

2021-04-19 09:32 UTC, 0x91 approved these changes

2021-04-19 10:39 UTC, merged